require('dotenv').config();

const {
  MONGODB_URI,
  PORT,
  JWT_SECRET,
  NODE_ENV,
  GMAIL_USER,
  GMAIL_PASS,
  AWS_ACCESS_KEY_ID,
  AWS_BUCKET_NAME,
  AWS_REGION,
  AWS_SECRET_ACCESS_KEY,
  AWS_S3_BASE_URL,
} = process.env;

module.exports = {
  MONGODB_URI,
  PORT,
  JWT_SECRET,
  NODE_ENV,
  GMAIL_USER,
  GMAIL_PASS,
  AWS_DATA: {
    AWS_SECRET_ACCESS_KEY,
    AWS_ACCESS_KEY_ID,
    AWS_REGION,
    AWS_BUCKET_NAME,
    AWS_S3_BASE_URL,
  },
};
